apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: pxe-demo
  name: pxe-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      run: pxe-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: pxe-demo
    spec:
      containers:
      - image: nj93/pxe-demo
        name: pxe-demo
        ports:
        - containerPort: 8080
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
        
status: {}
